spring:
  application:
    name: fd-zuul-service

server:
  port: 9070

eureka:
  server:
    host: localhost:8761
    contextPath: serviceregistry
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://${eureka.server.host}/${eureka.server.contextPath}/eureka}
  instance:
    preferIpAddress: true
    
logging:
  loglevel:
    demo:  ${LOG_LEVEL_DEMO:DEBUG}
    root: ${LOG_LEVEL_ROOT:DEBUG}
    springframework: ${LOG_LEVEL_SPRINGFRAMEWORK:DEBUG}
    apachewire:  ${LOG_LEVEL_SPRINGFRAMEWORK:ERROR}
  config: ${LOG_CONFIG_LOCATION:classpath:logback-spring-default.xml}
  
  
zuul:
  routes:
    client1:
      sensitiveHeaders:
      path: /service1/**
      serviceId: fd-user-service
    client2:
      sensitiveHeaders:
      path: /service2/**
      serviceId: fd-user-feign-client