fd:
  microservice:
    user:
      name: fd-user-service

spring:
  application:
    name: fd-user-feign-client

server:
  port: 8080

eureka:
  server:
    host: localhost:8761
    contextPath: serviceregistry
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://${eureka.server.host}/${eureka.server.contextPath}/eureka}
  instance:
    preferIpAddress: true
    
logging:
  loglevel:
    demo:  ${LOG_LEVEL_DEMO:DEBUG}
    root: ${LOG_LEVEL_ROOT:DEBUG}
    springframework: ${LOG_LEVEL_SPRINGFRAMEWORK:DEBUG}
    apachewire:  ${LOG_LEVEL_SPRINGFRAMEWORK:ERROR}
  config: ${LOG_CONFIG_LOCATION:classpath:logback-spring-default.xml}